// AUTO-GENERATED by scripts/generate-abis.sh (readable-name variant) — do not edit.
export const ZEROLANCE_POINTS_LEDGER_ABI = [
    {
        "type": "constructor",
        "inputs": [
            {
                "name": "owner_",
                "type": "address",
                "internalType": "address"
            }
        ],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "awardBase",
        "inputs": [
            {
                "name": "waveId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "contributor",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "points",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "refHash",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "awardCommunity",
        "inputs": [
            {
                "name": "waveId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "contributor",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "points",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "refHash",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "awardCompliment",
        "inputs": [
            {
                "name": "waveId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "contributor",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "points",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "refHash",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "contributorPoints",
        "inputs": [
            {
                "name": "waveId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "contributor",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "freezeWave",
        "inputs": [
            {
                "name": "waveId",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "isFrozen",
        "inputs": [
            {
                "name": "waveId",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "owner",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "address",
                "internalType": "address"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "setWaveOperator",
        "inputs": [
            {
                "name": "op",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "totalPoints",
        "inputs": [
            {
                "name": "waveId",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "waveOperator",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "address",
                "internalType": "address"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "event",
        "name": "PointsAwarded",
        "inputs": [
            {
                "name": "waveId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "contributor",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "kind",
                "type": "uint8",
                "indexed": false,
                "internalType": "enum IPointsLedger.AwardKind"
            },
            {
                "name": "points",
                "type": "uint96",
                "indexed": false,
                "internalType": "uint96"
            },
            {
                "name": "refHash",
                "type": "bytes32",
                "indexed": false,
                "internalType": "bytes32"
            }
        ],
        "anonymous": false
    },
    {
        "type": "error",
        "name": "NotAuthorized",
        "inputs": []
    },
    {
        "type": "error",
        "name": "WaveFrozen",
        "inputs": []
    },
    {
        "type": "error",
        "name": "ZeroAddress",
        "inputs": []
    },
    {
        "type": "error",
        "name": "ZeroPoints",
        "inputs": []
    }
];
//# sourceMappingURL=pointsLedger.js.map