// AUTO-GENERATED by scripts/generate-abis.sh (readable-name variant) — do not edit.
export const WAVE_FUNDING_VERIFIER_ABI = [
  {
    "type": "constructor",
    "inputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "UPGRADE_INTERFACE_VERSION",
    "inputs": [],
    "outputs": [
      { "name": "", "type": "string", "internalType": "string" }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "awardBase",
    "inputs": [
      { "name": "waveId", "type": "uint256", "internalType": "uint256" },
      { "name": "contributor", "type": "address", "internalType": "address" },
      { "name": "points", "type": "uint256", "internalType": "uint256" },
      { "name": "refHash", "type": "bytes32", "internalType": "bytes32" }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "awardCommunity",
    "inputs": [
      { "name": "waveId", "type": "uint256", "internalType": "uint256" },
      { "name": "contributor", "type": "address", "internalType": "address" },
      { "name": "points", "type": "uint256", "internalType": "uint256" },
      { "name": "refHash", "type": "bytes32", "internalType": "bytes32" }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "awardCompliment",
    "inputs": [
      { "name": "waveId", "type": "uint256", "internalType": "uint256" },
      { "name": "contributor", "type": "address", "internalType": "address" },
      { "name": "points", "type": "uint256", "internalType": "uint256" },
      { "name": "refHash", "type": "bytes32", "internalType": "bytes32" }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "claim",
    "inputs": [
      { "name": "programId", "type": "uint256", "internalType": "uint256" },
      { "name": "waveId", "type": "uint256", "internalType": "uint256" }
    ],
    "outputs": [
      { "name": "amount", "type": "uint256", "internalType": "uint256" }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "claimableShare",
    "inputs": [
      { "name": "programId", "type": "uint256", "internalType": "uint256" },
      { "name": "waveId", "type": "uint256", "internalType": "uint256" },
      { "name": "who", "type": "address", "internalType": "address" }
    ],
    "outputs": [
      { "name": "", "type": "uint256", "internalType": "uint256" }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "claimed",
    "inputs": [
      { "name": "programId", "type": "uint256", "internalType": "uint256" },
      { "name": "waveId", "type": "uint256", "internalType": "uint256" },
      { "name": "who", "type": "address", "internalType": "address" }
    ],
    "outputs": [
      { "name": "", "type": "bool", "internalType": "bool" }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "closeEvaluation",
    "inputs": [
      { "name": "programId", "type": "uint256", "internalType": "uint256" },
      { "name": "waveId", "type": "uint256", "internalType": "uint256" }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "closeProgram",
    "inputs": [
      { "name": "programId", "type": "uint256", "internalType": "uint256" }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "closeWave",
    "inputs": [
      { "name": "programId", "type": "uint256", "internalType": "uint256" },
      { "name": "waveId", "type": "uint256", "internalType": "uint256" }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "createWaveProgram",
    "inputs": [
      { "name": "token", "type": "address", "internalType": "address" },
      { "name": "genesisPool", "type": "uint256", "internalType": "uint256" },
      { "name": "numWaves", "type": "uint16", "internalType": "uint16" },
      { "name": "buildWindow", "type": "uint64", "internalType": "uint64" },
      { "name": "evalWindow", "type": "uint64", "internalType": "uint64" },
      { "name": "complimentWindow", "type": "uint64", "internalType": "uint64" },
      { "name": "budgetMethod", "type": "uint8", "internalType": "uint8" },
      { "name": "feeBps", "type": "uint16", "internalType": "uint16" },
      { "name": "treasury", "type": "address", "internalType": "address" },
      { "name": "specHash", "type": "bytes32", "internalType": "bytes32" }
    ],
    "outputs": [
      { "name": "programId", "type": "uint256", "internalType": "uint256" }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "currentOpenWave",
    "inputs": [
      { "name": "programId", "type": "uint256", "internalType": "uint256" }
    ],
    "outputs": [
      { "name": "", "type": "uint256", "internalType": "uint256" }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "depositPool",
    "inputs": [
      { "name": "programId", "type": "uint256", "internalType": "uint256" },
      { "name": "amount", "type": "uint256", "internalType": "uint256" }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "escrow",
    "inputs": [],
    "outputs": [
      { "name": "", "type": "address", "internalType": "address" }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "finalizeWave",
    "inputs": [
      { "name": "programId", "type": "uint256", "internalType": "uint256" },
      { "name": "waveId", "type": "uint256", "internalType": "uint256" }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "grantAwarder",
    "inputs": [
      { "name": "programId", "type": "uint256", "internalType": "uint256" },
      { "name": "who", "type": "address", "internalType": "address" },
      { "name": "allowed", "type": "bool", "internalType": "bool" }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "initialize",
    "inputs": [
      { "name": "admin", "type": "address", "internalType": "address" },
      { "name": "escrow", "type": "address", "internalType": "address" },
      { "name": "pointsLedger", "type": "address", "internalType": "address" }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "openWave",
    "inputs": [
      { "name": "programId", "type": "uint256", "internalType": "uint256" }
    ],
    "outputs": [
      { "name": "waveId", "type": "uint256", "internalType": "uint256" }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      { "name": "", "type": "address", "internalType": "address" }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pause",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "paused",
    "inputs": [],
    "outputs": [
      { "name": "", "type": "bool", "internalType": "bool" }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pointsLedger",
    "inputs": [],
    "outputs": [
      { "name": "", "type": "address", "internalType": "address" }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "project",
    "inputs": [
      { "name": "projectId", "type": "uint256", "internalType": "uint256" }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IWaveFundingVerifier.Project",
        "components": [
          { "name": "programId", "type": "uint256", "internalType": "uint256" },
          { "name": "waveId", "type": "uint256", "internalType": "uint256" },
          { "name": "wallet", "type": "address", "internalType": "address" },
          { "name": "repoHash", "type": "bytes32", "internalType": "bytes32" },
          { "name": "repoUrl", "type": "string", "internalType": "string" },
          { "name": "points", "type": "uint256", "internalType": "uint256" }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "program",
    "inputs": [
      { "name": "programId", "type": "uint256", "internalType": "uint256" }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IWaveFundingVerifier.Program",
        "components": [
          { "name": "organizer", "type": "address", "internalType": "address" },
          { "name": "token", "type": "address", "internalType": "address" },
          { "name": "genesisPool", "type": "uint256", "internalType": "uint256" },
          { "name": "numWaves", "type": "uint16", "internalType": "uint16" },
          { "name": "buildWindow", "type": "uint64", "internalType": "uint64" },
          { "name": "evalWindow", "type": "uint64", "internalType": "uint64" },
          { "name": "complimentWindow", "type": "uint64", "internalType": "uint64" },
          { "name": "budgetMethod", "type": "uint8", "internalType": "uint8" },
          { "name": "feeBps", "type": "uint16", "internalType": "uint16" },
          { "name": "treasury", "type": "address", "internalType": "address" },
          { "name": "specHash", "type": "bytes32", "internalType": "bytes32" },
          { "name": "initialized", "type": "bool", "internalType": "bool" }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "proxiableUUID",
    "inputs": [],
    "outputs": [
      { "name": "", "type": "bytes32", "internalType": "bytes32" }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registerProject",
    "inputs": [
      { "name": "programId", "type": "uint256", "internalType": "uint256" },
      { "name": "waveId", "type": "uint256", "internalType": "uint256" },
      { "name": "wallet", "type": "address", "internalType": "address" },
      { "name": "repoUrl", "type": "string", "internalType": "string" }
    ],
    "outputs": [
      { "name": "projectId", "type": "uint256", "internalType": "uint256" }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "remainingPool",
    "inputs": [
      { "name": "programId", "type": "uint256", "internalType": "uint256" }
    ],
    "outputs": [
      { "name": "", "type": "uint256", "internalType": "uint256" }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setPointsLedger",
    "inputs": [
      { "name": "ledger", "type": "address", "internalType": "address" }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setProjectPoints",
    "inputs": [
      { "name": "programId", "type": "uint256", "internalType": "uint256" },
      { "name": "projectId", "type": "uint256", "internalType": "uint256" },
      { "name": "points", "type": "uint256", "internalType": "uint256" }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "totalClaimable",
    "inputs": [
      { "name": "programId", "type": "uint256", "internalType": "uint256" },
      { "name": "waveId", "type": "uint256", "internalType": "uint256" }
    ],
    "outputs": [
      { "name": "", "type": "uint256", "internalType": "uint256" }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      { "name": "newOwner", "type": "address", "internalType": "address" }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "unpause",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "upgradeToAndCall",
    "inputs": [
      { "name": "newImplementation", "type": "address", "internalType": "address" },
      { "name": "data", "type": "bytes", "internalType": "bytes" }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "wave",
    "inputs": [
      { "name": "waveId", "type": "uint256", "internalType": "uint256" }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IWaveFundingVerifier.Wave",
        "components": [
          { "name": "programId", "type": "uint256", "internalType": "uint256" },
          { "name": "seq", "type": "uint256", "internalType": "uint256" },
          { "name": "status", "type": "uint8", "internalType": "uint8" },
          { "name": "buildEndAt", "type": "uint256", "internalType": "uint256" },
          { "name": "evalEndAt", "type": "uint256", "internalType": "uint256" }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "waveBudget",
    "inputs": [
      { "name": "programId", "type": "uint256", "internalType": "uint256" },
      { "name": "waveId", "type": "uint256", "internalType": "uint256" }
    ],
    "outputs": [
      { "name": "", "type": "uint256", "internalType": "uint256" }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "waveCount",
    "inputs": [
      { "name": "programId", "type": "uint256", "internalType": "uint256" }
    ],
    "outputs": [
      { "name": "", "type": "uint256", "internalType": "uint256" }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "waveProjects",
    "inputs": [
      { "name": "programId", "type": "uint256", "internalType": "uint256" },
      { "name": "waveId", "type": "uint256", "internalType": "uint256" }
    ],
    "outputs": [
      { "name": "", "type": "uint256[]", "internalType": "uint256[]" }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "AwarderSet",
    "inputs": [
      { "name": "programId", "type": "uint256", "indexed": true, "internalType": "uint256" },
      { "name": "awarder", "type": "address", "indexed": true, "internalType": "address" },
      { "name": "allowed", "type": "bool", "indexed": false, "internalType": "bool" }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EvaluationClosed",
    "inputs": [
      { "name": "programId", "type": "uint256", "indexed": true, "internalType": "uint256" },
      { "name": "waveId", "type": "uint256", "indexed": true, "internalType": "uint256" }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EvaluationOpened",
    "inputs": [
      { "name": "programId", "type": "uint256", "indexed": true, "internalType": "uint256" },
      { "name": "waveId", "type": "uint256", "indexed": true, "internalType": "uint256" },
      { "name": "evalEndAt", "type": "uint256", "indexed": false, "internalType": "uint256" }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Initialized",
    "inputs": [
      { "name": "version", "type": "uint64", "indexed": false, "internalType": "uint64" }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      { "name": "previousOwner", "type": "address", "indexed": true, "internalType": "address" },
      { "name": "newOwner", "type": "address", "indexed": true, "internalType": "address" }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Paused",
    "inputs": [
      { "name": "account", "type": "address", "indexed": false, "internalType": "address" }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PoolDeposited",
    "inputs": [
      { "name": "programId", "type": "uint256", "indexed": true, "internalType": "uint256" },
      { "name": "from", "type": "address", "indexed": true, "internalType": "address" },
      { "name": "amount", "type": "uint256", "indexed": false, "internalType": "uint256" }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ProgramClosed",
    "inputs": [
      { "name": "programId", "type": "uint256", "indexed": true, "internalType": "uint256" },
      { "name": "returned", "type": "uint256", "indexed": false, "internalType": "uint256" }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ProgramCreated",
    "inputs": [
      { "name": "programId", "type": "uint256", "indexed": true, "internalType": "uint256" },
      { "name": "organizer", "type": "address", "indexed": true, "internalType": "address" },
      { "name": "token", "type": "address", "indexed": false, "internalType": "address" },
      { "name": "genesisPool", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "numWaves", "type": "uint16", "indexed": false, "internalType": "uint16" },
      { "name": "budgetMethod", "type": "uint8", "indexed": false, "internalType": "uint8" },
      { "name": "feeBps", "type": "uint16", "indexed": false, "internalType": "uint16" },
      { "name": "treasury", "type": "address", "indexed": false, "internalType": "address" },
      { "name": "specHash", "type": "bytes32", "indexed": false, "internalType": "bytes32" }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ProjectPointsSet",
    "inputs": [
      { "name": "projectId", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "points", "type": "uint256", "indexed": false, "internalType": "uint256" }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ProjectRegistered",
    "inputs": [
      { "name": "programId", "type": "uint256", "indexed": true, "internalType": "uint256" },
      { "name": "waveId", "type": "uint256", "indexed": true, "internalType": "uint256" },
      { "name": "projectId", "type": "uint256", "indexed": true, "internalType": "uint256" },
      { "name": "wallet", "type": "address", "indexed": false, "internalType": "address" },
      { "name": "repoUrl", "type": "string", "indexed": false, "internalType": "string" },
      { "name": "repoHash", "type": "bytes32", "indexed": false, "internalType": "bytes32" }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Unpaused",
    "inputs": [
      { "name": "account", "type": "address", "indexed": false, "internalType": "address" }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Upgraded",
    "inputs": [
      { "name": "implementation", "type": "address", "indexed": true, "internalType": "address" }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "WaveClaimed",
    "inputs": [
      { "name": "programId", "type": "uint256", "indexed": true, "internalType": "uint256" },
      { "name": "waveId", "type": "uint256", "indexed": true, "internalType": "uint256" },
      { "name": "contributor", "type": "address", "indexed": true, "internalType": "address" },
      { "name": "amount", "type": "uint256", "indexed": false, "internalType": "uint256" }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "WaveClosed",
    "inputs": [
      { "name": "programId", "type": "uint256", "indexed": true, "internalType": "uint256" },
      { "name": "waveId", "type": "uint256", "indexed": true, "internalType": "uint256" }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "WaveFinalized",
    "inputs": [
      { "name": "programId", "type": "uint256", "indexed": true, "internalType": "uint256" },
      { "name": "waveId", "type": "uint256", "indexed": true, "internalType": "uint256" },
      { "name": "budget", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "netBudget", "type": "uint256", "indexed": false, "internalType": "uint256" }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "WaveOpened",
    "inputs": [
      { "name": "programId", "type": "uint256", "indexed": true, "internalType": "uint256" },
      { "name": "waveId", "type": "uint256", "indexed": true, "internalType": "uint256" },
      { "name": "seq", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "buildEndAt", "type": "uint256", "indexed": false, "internalType": "uint256" }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyClaimed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ERC1967InvalidImplementation",
    "inputs": [
      { "name": "implementation", "type": "address", "internalType": "address" }
    ]
  },
  {
    "type": "error",
    "name": "ERC1967NonPayable",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EnforcedPause",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ExpectedPause",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidBps",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidInitialization",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidNumWaves",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidParams",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotAwarder",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotInitializing",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotOrganizer",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotPointsLedgerOperator",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotProjectOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      { "name": "owner", "type": "address", "internalType": "address" }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      { "name": "account", "type": "address", "internalType": "address" }
    ]
  },
  {
    "type": "error",
    "name": "ProgramNotFound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ProjectNotFound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UUPSUnauthorizedCallContext",
    "inputs": [
      { "name": "slot", "type": "bytes32", "internalType": "bytes32" }
    ]
  },
  {
    "type": "error",
    "name": "UUPSUnsupportedProxiableUUID",
    "inputs": [
      { "name": "slot", "type": "bytes32", "internalType": "bytes32" }
    ]
  },
  {
    "type": "error",
    "name": "WaveNotFinalized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WaveNotFound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WaveSequenceExceeded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WrongWaveStatus",
    "inputs": [
      { "name": "expected", "type": "uint8", "internalType": "uint8" },
      { "name": "actual", "type": "uint8", "internalType": "uint8" }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroBudget",
    "inputs": []
  }
] as const;
