// AUTO-GENERATED by scripts/generate-abis.sh — do not edit.
export const ZEROLANCE_TEE_VERIFIER_ABI = [
    {
        "type": "constructor",
        "inputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "UPGRADE_INTERFACE_VERSION",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "string",
                "internalType": "string"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "cancelSignerProposal",
        "inputs": [],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "cleanExpiredProofs",
        "inputs": [
            {
                "name": "proofNonces",
                "type": "bytes32[]",
                "internalType": "bytes32[]"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "domainSeparator",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "executeSigner",
        "inputs": [],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "initialize",
        "inputs": [
            {
                "name": "_owner",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "_signer",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "_maxProofAge",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "maxProofAgeSeconds",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "owner",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "address",
                "internalType": "address"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "pendingSigner",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "address",
                "internalType": "address"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "proposeSigner",
        "inputs": [
            {
                "name": "newSigner",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "proxiableUUID",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "recoverVerdictSigner",
        "inputs": [
            {
                "name": "v",
                "type": "tuple",
                "internalType": "struct IZeroLanceTeeVerifier.Verdict",
                "components": [
                    {
                        "name": "taskId",
                        "type": "uint256",
                        "internalType": "uint256"
                    },
                    {
                        "name": "deliverableHash",
                        "type": "bytes32",
                        "internalType": "bytes32"
                    },
                    {
                        "name": "passed",
                        "type": "bool",
                        "internalType": "bool"
                    },
                    {
                        "name": "score",
                        "type": "uint256",
                        "internalType": "uint256"
                    },
                    {
                        "name": "nonce",
                        "type": "bytes32",
                        "internalType": "bytes32"
                    },
                    {
                        "name": "validUntil",
                        "type": "uint256",
                        "internalType": "uint256"
                    },
                    {
                        "name": "signature",
                        "type": "bytes",
                        "internalType": "bytes"
                    }
                ]
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "address",
                "internalType": "address"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "registeredSigner",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "address",
                "internalType": "address"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "renounceOwnership",
        "inputs": [],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "transferOwnership",
        "inputs": [
            {
                "name": "newOwner",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "upgradeToAndCall",
        "inputs": [
            {
                "name": "newImplementation",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "data",
                "type": "bytes",
                "internalType": "bytes"
            }
        ],
        "outputs": [],
        "stateMutability": "payable"
    },
    {
        "type": "function",
        "name": "verdictMessageHash",
        "inputs": [
            {
                "name": "v",
                "type": "tuple",
                "internalType": "struct IZeroLanceTeeVerifier.Verdict",
                "components": [
                    {
                        "name": "taskId",
                        "type": "uint256",
                        "internalType": "uint256"
                    },
                    {
                        "name": "deliverableHash",
                        "type": "bytes32",
                        "internalType": "bytes32"
                    },
                    {
                        "name": "passed",
                        "type": "bool",
                        "internalType": "bool"
                    },
                    {
                        "name": "score",
                        "type": "uint256",
                        "internalType": "uint256"
                    },
                    {
                        "name": "nonce",
                        "type": "bytes32",
                        "internalType": "bytes32"
                    },
                    {
                        "name": "validUntil",
                        "type": "uint256",
                        "internalType": "uint256"
                    },
                    {
                        "name": "signature",
                        "type": "bytes",
                        "internalType": "bytes"
                    }
                ]
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "verdictStructHash",
        "inputs": [
            {
                "name": "v",
                "type": "tuple",
                "internalType": "struct IZeroLanceTeeVerifier.Verdict",
                "components": [
                    {
                        "name": "taskId",
                        "type": "uint256",
                        "internalType": "uint256"
                    },
                    {
                        "name": "deliverableHash",
                        "type": "bytes32",
                        "internalType": "bytes32"
                    },
                    {
                        "name": "passed",
                        "type": "bool",
                        "internalType": "bool"
                    },
                    {
                        "name": "score",
                        "type": "uint256",
                        "internalType": "uint256"
                    },
                    {
                        "name": "nonce",
                        "type": "bytes32",
                        "internalType": "bytes32"
                    },
                    {
                        "name": "validUntil",
                        "type": "uint256",
                        "internalType": "uint256"
                    },
                    {
                        "name": "signature",
                        "type": "bytes",
                        "internalType": "bytes"
                    }
                ]
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "stateMutability": "pure"
    },
    {
        "type": "function",
        "name": "verifyTransferValidity",
        "inputs": [
            {
                "name": "proofs",
                "type": "tuple[]",
                "internalType": "struct TransferValidityProof[]",
                "components": [
                    {
                        "name": "accessProof",
                        "type": "tuple",
                        "internalType": "struct AccessProof",
                        "components": [
                            {
                                "name": "dataHash",
                                "type": "bytes32",
                                "internalType": "bytes32"
                            },
                            {
                                "name": "targetPubkey",
                                "type": "bytes",
                                "internalType": "bytes"
                            },
                            {
                                "name": "nonce",
                                "type": "bytes",
                                "internalType": "bytes"
                            },
                            {
                                "name": "proof",
                                "type": "bytes",
                                "internalType": "bytes"
                            },
                            {
                                "name": "validUntil",
                                "type": "uint256",
                                "internalType": "uint256"
                            }
                        ]
                    },
                    {
                        "name": "ownershipProof",
                        "type": "tuple",
                        "internalType": "struct OwnershipProof",
                        "components": [
                            {
                                "name": "oracleType",
                                "type": "uint8",
                                "internalType": "enum OracleType"
                            },
                            {
                                "name": "dataHash",
                                "type": "bytes32",
                                "internalType": "bytes32"
                            },
                            {
                                "name": "sealedKey",
                                "type": "bytes",
                                "internalType": "bytes"
                            },
                            {
                                "name": "targetPubkey",
                                "type": "bytes",
                                "internalType": "bytes"
                            },
                            {
                                "name": "nonce",
                                "type": "bytes",
                                "internalType": "bytes"
                            },
                            {
                                "name": "proof",
                                "type": "bytes",
                                "internalType": "bytes"
                            },
                            {
                                "name": "validUntil",
                                "type": "uint256",
                                "internalType": "uint256"
                            }
                        ]
                    }
                ]
            },
            {
                "name": "to",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "nft",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [
            {
                "name": "outputs",
                "type": "tuple[]",
                "internalType": "struct TransferValidityProofOutput[]",
                "components": [
                    {
                        "name": "dataHash",
                        "type": "bytes32",
                        "internalType": "bytes32"
                    },
                    {
                        "name": "sealedKey",
                        "type": "bytes",
                        "internalType": "bytes"
                    },
                    {
                        "name": "targetPubkey",
                        "type": "bytes",
                        "internalType": "bytes"
                    },
                    {
                        "name": "wantedKey",
                        "type": "bytes",
                        "internalType": "bytes"
                    },
                    {
                        "name": "accessAssistant",
                        "type": "address",
                        "internalType": "address"
                    },
                    {
                        "name": "accessProofNonce",
                        "type": "bytes",
                        "internalType": "bytes"
                    },
                    {
                        "name": "ownershipProofNonce",
                        "type": "bytes",
                        "internalType": "bytes"
                    }
                ]
            }
        ],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "verifyVerdict",
        "inputs": [
            {
                "name": "verdict",
                "type": "tuple",
                "internalType": "struct IZeroLanceTeeVerifier.Verdict",
                "components": [
                    {
                        "name": "taskId",
                        "type": "uint256",
                        "internalType": "uint256"
                    },
                    {
                        "name": "deliverableHash",
                        "type": "bytes32",
                        "internalType": "bytes32"
                    },
                    {
                        "name": "passed",
                        "type": "bool",
                        "internalType": "bool"
                    },
                    {
                        "name": "score",
                        "type": "uint256",
                        "internalType": "uint256"
                    },
                    {
                        "name": "nonce",
                        "type": "bytes32",
                        "internalType": "bytes32"
                    },
                    {
                        "name": "validUntil",
                        "type": "uint256",
                        "internalType": "uint256"
                    },
                    {
                        "name": "signature",
                        "type": "bytes",
                        "internalType": "bytes"
                    }
                ]
            }
        ],
        "outputs": [
            {
                "name": "valid",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "nonpayable"
    },
    {
        "type": "event",
        "name": "Initialized",
        "inputs": [
            {
                "name": "version",
                "type": "uint64",
                "indexed": false,
                "internalType": "uint64"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "OwnershipTransferred",
        "inputs": [
            {
                "name": "previousOwner",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "newOwner",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "SignerExecuted",
        "inputs": [
            {
                "name": "oldSigner",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "newSigner",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "SignerProposalCancelled",
        "inputs": [
            {
                "name": "cancelledSigner",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "SignerProposed",
        "inputs": [
            {
                "name": "newSigner",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "executableAt",
                "type": "uint256",
                "indexed": false,
                "internalType": "uint256"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "Upgraded",
        "inputs": [
            {
                "name": "implementation",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "type": "error",
        "name": "AddressEmptyCode",
        "inputs": [
            {
                "name": "target",
                "type": "address",
                "internalType": "address"
            }
        ]
    },
    {
        "type": "error",
        "name": "AxiomInvalidAccessProof",
        "inputs": []
    },
    {
        "type": "error",
        "name": "AxiomInvalidOwnershipProof",
        "inputs": []
    },
    {
        "type": "error",
        "name": "AxiomInvalidSigner",
        "inputs": []
    },
    {
        "type": "error",
        "name": "AxiomProofExpired",
        "inputs": [
            {
                "name": "validUntil",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "blockTimestamp",
                "type": "uint256",
                "internalType": "uint256"
            }
        ]
    },
    {
        "type": "error",
        "name": "AxiomValidUntilTooFar",
        "inputs": [
            {
                "name": "validUntil",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "blockTimestamp",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "maxProofAgeSeconds",
                "type": "uint256",
                "internalType": "uint256"
            }
        ]
    },
    {
        "type": "error",
        "name": "DelayNotElapsed",
        "inputs": [
            {
                "name": "remaining",
                "type": "uint256",
                "internalType": "uint256"
            }
        ]
    },
    {
        "type": "error",
        "name": "ECDSAInvalidSignature",
        "inputs": []
    },
    {
        "type": "error",
        "name": "ECDSAInvalidSignatureLength",
        "inputs": [
            {
                "name": "length",
                "type": "uint256",
                "internalType": "uint256"
            }
        ]
    },
    {
        "type": "error",
        "name": "ECDSAInvalidSignatureS",
        "inputs": [
            {
                "name": "s",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ]
    },
    {
        "type": "error",
        "name": "ERC1967InvalidImplementation",
        "inputs": [
            {
                "name": "implementation",
                "type": "address",
                "internalType": "address"
            }
        ]
    },
    {
        "type": "error",
        "name": "ERC1967NonPayable",
        "inputs": []
    },
    {
        "type": "error",
        "name": "FailedInnerCall",
        "inputs": []
    },
    {
        "type": "error",
        "name": "InvalidInitialization",
        "inputs": []
    },
    {
        "type": "error",
        "name": "NoPendingProposal",
        "inputs": []
    },
    {
        "type": "error",
        "name": "NotInitializing",
        "inputs": []
    },
    {
        "type": "error",
        "name": "OwnableInvalidOwner",
        "inputs": [
            {
                "name": "owner",
                "type": "address",
                "internalType": "address"
            }
        ]
    },
    {
        "type": "error",
        "name": "OwnableUnauthorizedAccount",
        "inputs": [
            {
                "name": "account",
                "type": "address",
                "internalType": "address"
            }
        ]
    },
    {
        "type": "error",
        "name": "ProofAlreadyUsed",
        "inputs": [
            {
                "name": "proofHash",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ]
    },
    {
        "type": "error",
        "name": "ProofFieldMismatch",
        "inputs": []
    },
    {
        "type": "error",
        "name": "UUPSUnauthorizedCallContext",
        "inputs": []
    },
    {
        "type": "error",
        "name": "UUPSUnsupportedProxiableUUID",
        "inputs": [
            {
                "name": "slot",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ]
    },
    {
        "type": "error",
        "name": "ZeroAddress",
        "inputs": []
    }
];
//# sourceMappingURL=zeroLanceTeeVerifier.js.map