// AUTO-GENERATED by scripts/generate-abis.sh (readable-name variant) — do not edit.
export const ZEROLANCE_WAVE_ISSUE_ABI = [
    {
        "type": "constructor",
        "inputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "MAX_BASE_POINTS",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "UPGRADE_INTERFACE_VERSION",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "string",
                "internalType": "string"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "acceptRepo",
        "inputs": [
            {
                "name": "programId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "repoHash",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "allowed",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "addCompliment",
        "inputs": [
            {
                "name": "issueId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "points",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "claimIssue",
        "inputs": [
            {
                "name": "issueId",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "confirmMerge",
        "inputs": [
            {
                "name": "issueId",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "createIssue",
        "inputs": [
            {
                "name": "programId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "repoHash",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "specHash",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "basePoints",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "complexity",
                "type": "uint64",
                "internalType": "uint64"
            }
        ],
        "outputs": [
            {
                "name": "issueId",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "currentWave",
        "inputs": [
            {
                "name": "programId",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [
            {
                "name": "waveId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "isOpen",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "initialize",
        "inputs": [
            {
                "name": "admin",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "waveProgram_",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "issue",
        "inputs": [
            {
                "name": "issueId",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "tuple",
                "internalType": "struct IZeroLanceWaveIssue.Issue",
                "components": [
                    {
                        "name": "programId",
                        "type": "uint256",
                        "internalType": "uint256"
                    },
                    {
                        "name": "waveId",
                        "type": "uint256",
                        "internalType": "uint256"
                    },
                    {
                        "name": "maintainer",
                        "type": "address",
                        "internalType": "address"
                    },
                    {
                        "name": "builder",
                        "type": "address",
                        "internalType": "address"
                    },
                    {
                        "name": "specHash",
                        "type": "bytes32",
                        "internalType": "bytes32"
                    },
                    {
                        "name": "repoHash",
                        "type": "bytes32",
                        "internalType": "bytes32"
                    },
                    {
                        "name": "basePoints",
                        "type": "uint256",
                        "internalType": "uint256"
                    },
                    {
                        "name": "bonusPoints",
                        "type": "uint256",
                        "internalType": "uint256"
                    },
                    {
                        "name": "deliveredPr",
                        "type": "uint256",
                        "internalType": "uint256"
                    },
                    {
                        "name": "deliverableHash",
                        "type": "bytes32",
                        "internalType": "bytes32"
                    },
                    {
                        "name": "complexity",
                        "type": "uint64",
                        "internalType": "uint64"
                    },
                    {
                        "name": "state",
                        "type": "uint8",
                        "internalType": "uint8"
                    },
                    {
                        "name": "pointsAwarded",
                        "type": "bool",
                        "internalType": "bool"
                    }
                ]
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "owner",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "address",
                "internalType": "address"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "paused",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "proxiableUUID",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "renounceOwnership",
        "inputs": [],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "setIssuePoints",
        "inputs": [
            {
                "name": "issueId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "basePoints",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "setManager",
        "inputs": [
            {
                "name": "m",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "submitPr",
        "inputs": [
            {
                "name": "issueId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "deliverableHash",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "prNumber",
                "type": "uint64",
                "internalType": "uint64"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "transferOwnership",
        "inputs": [
            {
                "name": "newOwner",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "upgradeToAndCall",
        "inputs": [
            {
                "name": "newImplementation",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "data",
                "type": "bytes",
                "internalType": "bytes"
            }
        ],
        "outputs": [],
        "stateMutability": "payable"
    },
    {
        "type": "event",
        "name": "ComplimentAdded",
        "inputs": [
            {
                "name": "issueId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "points",
                "type": "uint256",
                "indexed": false,
                "internalType": "uint256"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "Initialized",
        "inputs": [
            {
                "name": "version",
                "type": "uint64",
                "indexed": false,
                "internalType": "uint64"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "IssueClaimed",
        "inputs": [
            {
                "name": "issueId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "builder",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "waveId",
                "type": "uint256",
                "indexed": false,
                "internalType": "uint256"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "IssueCreated",
        "inputs": [
            {
                "name": "programId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "issueId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "maintainer",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "basePoints",
                "type": "uint256",
                "indexed": false,
                "internalType": "uint256"
            },
            {
                "name": "repoHash",
                "type": "bytes32",
                "indexed": false,
                "internalType": "bytes32"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "IssueMerged",
        "inputs": [
            {
                "name": "issueId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "builder",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "points",
                "type": "uint256",
                "indexed": false,
                "internalType": "uint256"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "IssuePointsSet",
        "inputs": [
            {
                "name": "issueId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "basePoints",
                "type": "uint256",
                "indexed": false,
                "internalType": "uint256"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "IssuePrSubmitted",
        "inputs": [
            {
                "name": "issueId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "deliverableHash",
                "type": "bytes32",
                "indexed": false,
                "internalType": "bytes32"
            },
            {
                "name": "prNumber",
                "type": "uint64",
                "indexed": false,
                "internalType": "uint64"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "OwnershipTransferred",
        "inputs": [
            {
                "name": "previousOwner",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "newOwner",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "Paused",
        "inputs": [
            {
                "name": "account",
                "type": "address",
                "indexed": false,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "RepoAccepted",
        "inputs": [
            {
                "name": "programId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "repoHash",
                "type": "bytes32",
                "indexed": true,
                "internalType": "bytes32"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "Unpaused",
        "inputs": [
            {
                "name": "account",
                "type": "address",
                "indexed": false,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "Upgraded",
        "inputs": [
            {
                "name": "implementation",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "type": "error",
        "name": "AddressEmptyCode",
        "inputs": [
            {
                "name": "target",
                "type": "address",
                "internalType": "address"
            }
        ]
    },
    {
        "type": "error",
        "name": "ERC1967InvalidImplementation",
        "inputs": [
            {
                "name": "implementation",
                "type": "address",
                "internalType": "address"
            }
        ]
    },
    {
        "type": "error",
        "name": "ERC1967NonPayable",
        "inputs": []
    },
    {
        "type": "error",
        "name": "EnforcedPause",
        "inputs": []
    },
    {
        "type": "error",
        "name": "ExpectedPause",
        "inputs": []
    },
    {
        "type": "error",
        "name": "FailedInnerCall",
        "inputs": []
    },
    {
        "type": "error",
        "name": "InvalidInitialization",
        "inputs": []
    },
    {
        "type": "error",
        "name": "InvalidPoints",
        "inputs": []
    },
    {
        "type": "error",
        "name": "IssueNotFound",
        "inputs": []
    },
    {
        "type": "error",
        "name": "NoWaveOpen",
        "inputs": []
    },
    {
        "type": "error",
        "name": "NotBuilder",
        "inputs": []
    },
    {
        "type": "error",
        "name": "NotInitializing",
        "inputs": []
    },
    {
        "type": "error",
        "name": "NotMaintainer",
        "inputs": []
    },
    {
        "type": "error",
        "name": "NotManager",
        "inputs": []
    },
    {
        "type": "error",
        "name": "NotOrganizer",
        "inputs": []
    },
    {
        "type": "error",
        "name": "OwnableInvalidOwner",
        "inputs": [
            {
                "name": "owner",
                "type": "address",
                "internalType": "address"
            }
        ]
    },
    {
        "type": "error",
        "name": "OwnableUnauthorizedAccount",
        "inputs": [
            {
                "name": "account",
                "type": "address",
                "internalType": "address"
            }
        ]
    },
    {
        "type": "error",
        "name": "PointsLocked",
        "inputs": []
    },
    {
        "type": "error",
        "name": "ReentrancyGuardReentrantCall",
        "inputs": []
    },
    {
        "type": "error",
        "name": "RepoNotAccepted",
        "inputs": []
    },
    {
        "type": "error",
        "name": "UUPSUnauthorizedCallContext",
        "inputs": []
    },
    {
        "type": "error",
        "name": "UUPSUnsupportedProxiableUUID",
        "inputs": [
            {
                "name": "slot",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ]
    },
    {
        "type": "error",
        "name": "WrongIssueState",
        "inputs": [
            {
                "name": "expected",
                "type": "uint8",
                "internalType": "enum IZeroLanceWaveIssue.IssueState"
            },
            {
                "name": "actual",
                "type": "uint8",
                "internalType": "enum IZeroLanceWaveIssue.IssueState"
            }
        ]
    }
];
//# sourceMappingURL=zeroLanceWaveIssue.js.map