// AUTO-GENERATED by scripts/generate-abis.sh — do not edit.
export const ZEROLANCE_TASK_REGISTRY_ABI = [
    {
        "type": "constructor",
        "inputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "UPGRADE_INTERFACE_VERSION",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "string",
                "internalType": "string"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "assignTask",
        "inputs": [
            {
                "name": "taskId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "freelancer",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "authorizedSetter",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "address",
                "internalType": "address"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "createTask",
        "inputs": [
            {
                "name": "specHash",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "category",
                "type": "uint8",
                "internalType": "enum IZeroLanceTaskRegistry.TaskCategory"
            },
            {
                "name": "paymentToken",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "reward",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "deadline",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "repoUrl",
                "type": "string",
                "internalType": "string"
            },
            {
                "name": "issueNumber",
                "type": "uint64",
                "internalType": "uint64"
            },
            {
                "name": "coverageGateBps",
                "type": "uint16",
                "internalType": "uint16"
            }
        ],
        "outputs": [
            {
                "name": "taskId",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "initialize",
        "inputs": [
            {
                "name": "admin",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "authorizedSetters_",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "nextTaskId",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "owner",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "address",
                "internalType": "address"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "pause",
        "inputs": [],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "paused",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "bool",
                "internalType": "bool"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "proxiableUUID",
        "inputs": [],
        "outputs": [
            {
                "name": "",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "renounceOwnership",
        "inputs": [],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "setAuthorizedSetter",
        "inputs": [
            {
                "name": "authorizedSetters_",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "setStatus",
        "inputs": [
            {
                "name": "taskId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "status",
                "type": "uint8",
                "internalType": "enum IZeroLanceTaskRegistry.TaskStatus"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "specHashOf",
        "inputs": [
            {
                "name": "taskId",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "submitDeliverable",
        "inputs": [
            {
                "name": "taskId",
                "type": "uint256",
                "internalType": "uint256"
            },
            {
                "name": "deliverableHash",
                "type": "bytes32",
                "internalType": "bytes32"
            },
            {
                "name": "prNumber",
                "type": "uint64",
                "internalType": "uint64"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "taskOf",
        "inputs": [
            {
                "name": "taskId",
                "type": "uint256",
                "internalType": "uint256"
            }
        ],
        "outputs": [
            {
                "name": "",
                "type": "tuple",
                "internalType": "struct IZeroLanceTaskRegistry.Task",
                "components": [
                    {
                        "name": "client",
                        "type": "address",
                        "internalType": "address"
                    },
                    {
                        "name": "freelancer",
                        "type": "address",
                        "internalType": "address"
                    },
                    {
                        "name": "status",
                        "type": "uint8",
                        "internalType": "enum IZeroLanceTaskRegistry.TaskStatus"
                    },
                    {
                        "name": "category",
                        "type": "uint8",
                        "internalType": "enum IZeroLanceTaskRegistry.TaskCategory"
                    },
                    {
                        "name": "specHash",
                        "type": "bytes32",
                        "internalType": "bytes32"
                    },
                    {
                        "name": "deliverableHash",
                        "type": "bytes32",
                        "internalType": "bytes32"
                    },
                    {
                        "name": "paymentToken",
                        "type": "address",
                        "internalType": "address"
                    },
                    {
                        "name": "reward",
                        "type": "uint256",
                        "internalType": "uint256"
                    },
                    {
                        "name": "deadline",
                        "type": "uint256",
                        "internalType": "uint256"
                    },
                    {
                        "name": "createdAt",
                        "type": "uint256",
                        "internalType": "uint256"
                    },
                    {
                        "name": "retryDeadline",
                        "type": "uint256",
                        "internalType": "uint256"
                    },
                    {
                        "name": "repoUrl",
                        "type": "string",
                        "internalType": "string"
                    },
                    {
                        "name": "issueNumber",
                        "type": "uint64",
                        "internalType": "uint64"
                    },
                    {
                        "name": "prNumber",
                        "type": "uint64",
                        "internalType": "uint64"
                    },
                    {
                        "name": "coverageGateBps",
                        "type": "uint16",
                        "internalType": "uint16"
                    }
                ]
            }
        ],
        "stateMutability": "view"
    },
    {
        "type": "function",
        "name": "transferOwnership",
        "inputs": [
            {
                "name": "newOwner",
                "type": "address",
                "internalType": "address"
            }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "unpause",
        "inputs": [],
        "outputs": [],
        "stateMutability": "nonpayable"
    },
    {
        "type": "function",
        "name": "upgradeToAndCall",
        "inputs": [
            {
                "name": "newImplementation",
                "type": "address",
                "internalType": "address"
            },
            {
                "name": "data",
                "type": "bytes",
                "internalType": "bytes"
            }
        ],
        "outputs": [],
        "stateMutability": "payable"
    },
    {
        "type": "event",
        "name": "DeliverableSubmitted",
        "inputs": [
            {
                "name": "taskId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "freelancer",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "deliverableHash",
                "type": "bytes32",
                "indexed": false,
                "internalType": "bytes32"
            },
            {
                "name": "prNumber",
                "type": "uint64",
                "indexed": false,
                "internalType": "uint64"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "Initialized",
        "inputs": [
            {
                "name": "version",
                "type": "uint64",
                "indexed": false,
                "internalType": "uint64"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "OwnershipTransferred",
        "inputs": [
            {
                "name": "previousOwner",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "newOwner",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "Paused",
        "inputs": [
            {
                "name": "account",
                "type": "address",
                "indexed": false,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "TaskAssigned",
        "inputs": [
            {
                "name": "taskId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "freelancer",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "TaskCreated",
        "inputs": [
            {
                "name": "taskId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "client",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            },
            {
                "name": "specHash",
                "type": "bytes32",
                "indexed": true,
                "internalType": "bytes32"
            },
            {
                "name": "category",
                "type": "uint8",
                "indexed": false,
                "internalType": "enum IZeroLanceTaskRegistry.TaskCategory"
            },
            {
                "name": "reward",
                "type": "uint256",
                "indexed": false,
                "internalType": "uint256"
            },
            {
                "name": "deadline",
                "type": "uint256",
                "indexed": false,
                "internalType": "uint256"
            },
            {
                "name": "repoUrl",
                "type": "string",
                "indexed": false,
                "internalType": "string"
            },
            {
                "name": "issueNumber",
                "type": "uint64",
                "indexed": false,
                "internalType": "uint64"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "TaskStatusChanged",
        "inputs": [
            {
                "name": "taskId",
                "type": "uint256",
                "indexed": true,
                "internalType": "uint256"
            },
            {
                "name": "status",
                "type": "uint8",
                "indexed": false,
                "internalType": "enum IZeroLanceTaskRegistry.TaskStatus"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "Unpaused",
        "inputs": [
            {
                "name": "account",
                "type": "address",
                "indexed": false,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "type": "event",
        "name": "Upgraded",
        "inputs": [
            {
                "name": "implementation",
                "type": "address",
                "indexed": true,
                "internalType": "address"
            }
        ],
        "anonymous": false
    },
    {
        "type": "error",
        "name": "AddressEmptyCode",
        "inputs": [
            {
                "name": "target",
                "type": "address",
                "internalType": "address"
            }
        ]
    },
    {
        "type": "error",
        "name": "AlreadyAssigned",
        "inputs": []
    },
    {
        "type": "error",
        "name": "DeadlineInPast",
        "inputs": []
    },
    {
        "type": "error",
        "name": "ERC1967InvalidImplementation",
        "inputs": [
            {
                "name": "implementation",
                "type": "address",
                "internalType": "address"
            }
        ]
    },
    {
        "type": "error",
        "name": "ERC1967NonPayable",
        "inputs": []
    },
    {
        "type": "error",
        "name": "EmptyRepoUrl",
        "inputs": []
    },
    {
        "type": "error",
        "name": "EnforcedPause",
        "inputs": []
    },
    {
        "type": "error",
        "name": "ExpectedPause",
        "inputs": []
    },
    {
        "type": "error",
        "name": "FailedInnerCall",
        "inputs": []
    },
    {
        "type": "error",
        "name": "InvalidCoverageGate",
        "inputs": []
    },
    {
        "type": "error",
        "name": "InvalidInitialization",
        "inputs": []
    },
    {
        "type": "error",
        "name": "NotAssigned",
        "inputs": []
    },
    {
        "type": "error",
        "name": "NotClient",
        "inputs": []
    },
    {
        "type": "error",
        "name": "NotFreelancer",
        "inputs": []
    },
    {
        "type": "error",
        "name": "NotInitializing",
        "inputs": []
    },
    {
        "type": "error",
        "name": "OwnableInvalidOwner",
        "inputs": [
            {
                "name": "owner",
                "type": "address",
                "internalType": "address"
            }
        ]
    },
    {
        "type": "error",
        "name": "OwnableUnauthorizedAccount",
        "inputs": [
            {
                "name": "account",
                "type": "address",
                "internalType": "address"
            }
        ]
    },
    {
        "type": "error",
        "name": "ReentrancyGuardReentrantCall",
        "inputs": []
    },
    {
        "type": "error",
        "name": "UUPSUnauthorizedCallContext",
        "inputs": []
    },
    {
        "type": "error",
        "name": "UUPSUnsupportedProxiableUUID",
        "inputs": [
            {
                "name": "slot",
                "type": "bytes32",
                "internalType": "bytes32"
            }
        ]
    },
    {
        "type": "error",
        "name": "WrongStatus",
        "inputs": [
            {
                "name": "expected",
                "type": "uint8",
                "internalType": "enum IZeroLanceTaskRegistry.TaskStatus"
            },
            {
                "name": "actual",
                "type": "uint8",
                "internalType": "enum IZeroLanceTaskRegistry.TaskStatus"
            }
        ]
    },
    {
        "type": "error",
        "name": "ZeroAddress",
        "inputs": []
    },
    {
        "type": "error",
        "name": "ZeroAmount",
        "inputs": []
    },
    {
        "type": "error",
        "name": "ZeroSpecHash",
        "inputs": []
    }
];
//# sourceMappingURL=zeroLanceTaskRegistry.js.map