import { z } from "zod";
export declare const sharedEnvSchema: z.ZodObject<{
    ZERO_FRONTEND_URL: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>;
    ZERO_API_KEY: z.ZodOptional<z.ZodString>;
    ZERO_COMPUTE_API_KEY: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>;
    ZERO_CHAIN_ID: z.ZodDefault<z.ZodNumber>;
    OG_COMPUTE_BASE_URL: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>;
    ZERO_EVM_RPC: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>;
    ZERO_ORACLE_URL: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>;
    ZERO_TEE_SIGNER_PK: z.ZodOptional<z.ZodString>;
    ZERO_SENTRY_DSN: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>;
    ZERO_COMPUTE_BASE_URL: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>;
    ZERO_DISABLE_AUTH: z.ZodOptional<z.ZodString>;
    ZERO_COMPUTE_DIRECT_KEY: z.ZodOptional<z.ZodString>;
    ZERO_COMPUTE_DIRECT_URL: z.ZodEffects<z.ZodOptional<z.ZodString>, string | undefined, unknown>;
    ZERO_CLIENT_API_KEY: z.ZodOptional<z.ZodString>;
    ZERO_EVENT_SOURCES: z.ZodOptional<z.ZodString>;
    ZERO_HEALTH_CACHE_MS: z.ZodOptional<z.ZodNumber>;
    ZERO_RATE_LIMIT_MAX: z.ZodDefault<z.ZodNumber>;
    ZERO_CHAT_STREAM_TIMEOUT_MS: z.ZodOptional<z.ZodNumber>;
    ZERO_DATA_DIR: z.ZodOptional<z.ZodString>;
    ZERO_GITHUB_TOKEN: z.ZodOptional<z.ZodString>;
    ZERO_SANDBOX_IMAGE: z.ZodOptional<z.ZodString>;
    ZERO_VERIFICATION_TIMEOUT_MS: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    ZERO_CHAIN_ID: number;
    ZERO_RATE_LIMIT_MAX: number;
    ZERO_EVM_RPC?: string | undefined;
    ZERO_DATA_DIR?: string | undefined;
    ZERO_ORACLE_URL?: string | undefined;
    ZERO_SENTRY_DSN?: string | undefined;
    ZERO_COMPUTE_API_KEY?: string | undefined;
    ZERO_TEE_SIGNER_PK?: string | undefined;
    ZERO_GITHUB_TOKEN?: string | undefined;
    ZERO_SANDBOX_IMAGE?: string | undefined;
    ZERO_VERIFICATION_TIMEOUT_MS?: number | undefined;
    ZERO_FRONTEND_URL?: string | undefined;
    ZERO_API_KEY?: string | undefined;
    OG_COMPUTE_BASE_URL?: string | undefined;
    ZERO_COMPUTE_BASE_URL?: string | undefined;
    ZERO_DISABLE_AUTH?: string | undefined;
    ZERO_COMPUTE_DIRECT_KEY?: string | undefined;
    ZERO_COMPUTE_DIRECT_URL?: string | undefined;
    ZERO_CLIENT_API_KEY?: string | undefined;
    ZERO_EVENT_SOURCES?: string | undefined;
    ZERO_HEALTH_CACHE_MS?: number | undefined;
    ZERO_CHAT_STREAM_TIMEOUT_MS?: number | undefined;
}, {
    ZERO_EVM_RPC?: unknown;
    ZERO_DATA_DIR?: string | undefined;
    ZERO_ORACLE_URL?: unknown;
    ZERO_SENTRY_DSN?: unknown;
    ZERO_COMPUTE_API_KEY?: unknown;
    ZERO_TEE_SIGNER_PK?: string | undefined;
    ZERO_GITHUB_TOKEN?: string | undefined;
    ZERO_SANDBOX_IMAGE?: string | undefined;
    ZERO_VERIFICATION_TIMEOUT_MS?: number | undefined;
    ZERO_FRONTEND_URL?: unknown;
    ZERO_API_KEY?: string | undefined;
    ZERO_CHAIN_ID?: number | undefined;
    OG_COMPUTE_BASE_URL?: unknown;
    ZERO_COMPUTE_BASE_URL?: unknown;
    ZERO_DISABLE_AUTH?: string | undefined;
    ZERO_COMPUTE_DIRECT_KEY?: string | undefined;
    ZERO_COMPUTE_DIRECT_URL?: unknown;
    ZERO_CLIENT_API_KEY?: string | undefined;
    ZERO_EVENT_SOURCES?: string | undefined;
    ZERO_HEALTH_CACHE_MS?: number | undefined;
    ZERO_RATE_LIMIT_MAX?: number | undefined;
    ZERO_CHAT_STREAM_TIMEOUT_MS?: number | undefined;
}>;
//# sourceMappingURL=env-schema.d.ts.map