#!/usr/bin/env bash
# Generate TypeScript ABI files from Foundry artifacts.
# Run after `forge build`. Emits one .ts file per contract into packages/config/src/abis/.
set -euo pipefail

CONTRACTS_DIR="$(cd "$(dirname "$0")/.." && pwd)/src"
ABIS_DIR="$(cd "$(dirname "$0")/../../../.." && pwd)/packages/config/src/abis"
OUT_DIR="$CONTRACTS_DIR/../out"

if [ ! -d "$OUT_DIR" ]; then
  echo "ERROR: $OUT_DIR not found — run 'forge build' first." >&2
  exit 1
fi

mkdir -p "$ABIS_DIR"

emit() {
  local name="$1"
  local artifact="$OUT_DIR/${name}.sol/${name}.json"
  if [ ! -f "$artifact" ]; then
    echo "WARN: artifact for $name not found at $artifact" >&2
    return 0
  fi
  local out="$ABIS_DIR/$(echo "$name" | sed 's/^./\L&/') .ts"
  out="$(echo "$out" | tr -d ' ')"
  {
    echo "// AUTO-GENERATED by scripts/generate-abis.sh — do not edit."
    echo "import type { readonly string[] } from \"../types/contract.js\";"
    echo "export const ${name^^}_ABI = $(jq '.abi' "$artifact") as const;"
  } > "$out"
  echo "wrote $out"
}

emit MockUSDC
emit ZeroLanceToken
emit ZeroLanceTeeVerifier
emit ZeroLanceTaskRegistry
emit ZeroLanceEscrowVault
emit ZeroLanceArbitration
emit ZeroLanceReputationNFT

# Regenerate the barrel.
{
  echo "// AUTO-GENERATED by scripts/generate-abis.sh — do not edit."
  echo "export { MOCK_USDC_ABI } from \"./mockUsdc.js\";"
  echo "export { ZEROLANCE_TOKEN_ABI } from \"./zeroLanceToken.js\";"
  echo "export { ZEROLANCE_TEE_VERIFIER_ABI } from \"./zeroLanceTeeVerifier.js\";"
  echo "export { ZEROLANCE_TASK_REGISTRY_ABI } from \"./zeroLanceTaskRegistry.js\";"
  echo "export { ZEROLANCE_ESCROW_VAULT_ABI } from \"./zeroLanceEscrowVault.js\";"
  echo "export { ZEROLANCE_ARBITRATION_ABI } from \"./zeroLanceArbitration.js\";"
  echo "export { ZEROLANCE_REPUTATION_NFT_ABI } from \"./zeroLanceReputationNft.js\";"
  echo "export { ERC20_ABI } from \"./erc20.js\";"
} > "$ABIS_DIR/index.ts"
echo "wrote $ABIS_DIR/index.ts"
