#!/usr/bin/env bash
# Generate TypeScript ABI files from Foundry artifacts.
# Run after `forge build`. Emits one .ts file per contract into packages/config/src/abis/.
set -euo pipefail

CONTRACTS_DIR="$(cd "$(dirname "$0")/.." && pwd)/src"
ABIS_DIR="$(cd "$(dirname "$0")/../../.." && pwd)/packages/config/src/abis"
OUT_DIR="$CONTRACTS_DIR/../out"

if [ ! -d "$OUT_DIR" ]; then
  echo "ERROR: $OUT_DIR not found — run 'forge build' first." >&2
  exit 1
fi

mkdir -p "$ABIS_DIR"

emit() {
  local name="$1"
  local constName="$2"
  local artifact="$OUT_DIR/${name}.sol/${name}.json"
  if [ ! -f "$artifact" ]; then
    echo "WARN: artifact for $name not found at $artifact" >&2
    return 0
  fi
  if [ -z "$constName" ]; then
    constName="${name^^}_ABI"
  fi
  local out="$ABIS_DIR/$(echo "$name" | sed 's/^./\L&/') .ts"
  out="$(echo "$out" | tr -d ' ')"
  {
    echo "// AUTO-GENERATED by scripts/generate-abis.sh — do not edit."
    echo "export const ${constName} = $(jq '.abi' "$artifact") as const;"
  } > "$out"
  echo "wrote $out"
}

# Historic contracts use their readable snake-case const names (backwards-compat
# with the curated names that preceded the generator).
emit MockUSDC MOCK_USDC_ABI
emit ZeroLanceToken ZEROLANCE_TOKEN_ABI
emit ZeroLanceTeeVerifier ZEROLANCE_TEE_VERIFIER_ABI
emit ZeroLanceTaskRegistry ZEROLANCE_TASK_REGISTRY_ABI
emit ZeroLanceEscrowVault ZEROLANCE_ESCROW_VAULT_ABI
emit ZeroLanceArbitration ZEROLANCE_ARBITRATION_ABI
emit ZeroLanceReputationNFT ZEROLANCE_REPUTATION_NFT_ABI
# Wave funding contracts — readable const names matching the barrel exports.
emit PointsLedger ZEROLANCE_POINTS_LEDGER_ABI
emit ZeroLanceWaveProgram ZEROLANCE_WAVE_PROGRAM_ABI
emit ZeroLanceWaveIssue ZEROLANCE_WAVE_ISSUE_ABI
emit ZeroLanceWaveBuildathon ZEROLANCE_WAVE_BUILDATHON_ABI

# Regenerate the barrel.
{
  echo "// AUTO-GENERATED by scripts/generate-abis.sh — do not edit."
  echo "export { MOCK_USDC_ABI } from \"./mockUSDC.js\";"
  echo "export { ZEROLANCE_TOKEN_ABI } from \"./zeroLanceToken.js\";"
  echo "export { ZEROLANCE_TEE_VERIFIER_ABI } from \"./zeroLanceTeeVerifier.js\";"
  echo "export { ZEROLANCE_TASK_REGISTRY_ABI } from \"./zeroLanceTaskRegistry.js\";"
  echo "export { ZEROLANCE_ESCROW_VAULT_ABI } from \"./zeroLanceEscrowVault.js\";"
  echo "export { ZEROLANCE_ARBITRATION_ABI } from \"./zeroLanceArbitration.js\";"
  echo "export { ZEROLANCE_REPUTATION_NFT_ABI } from \"./zeroLanceReputationNFT.js\";"
  echo "export { ZEROLANCE_POINTS_LEDGER_ABI } from \"./pointsLedger.js\";"
  echo "export { ZEROLANCE_WAVE_PROGRAM_ABI } from \"./zeroLanceWaveProgram.js\";"
  echo "export { ZEROLANCE_WAVE_ISSUE_ABI } from \"./zeroLanceWaveIssue.js\";"
  echo "export { ZEROLANCE_WAVE_BUILDATHON_ABI } from \"./zeroLanceWaveBuildathon.js\";"
  echo "export { ERC20_ABI } from \"./erc20.js\";"
} > "$ABIS_DIR/index.ts"
echo "wrote $ABIS_DIR/index.ts"
