export {
  ZEROLANCE_WAVE_PROGRAM_ABI,
  ZEROLANCE_WAVE_ISSUE_ABI,
  ZEROLANCE_WAVE_BUILDATHON_ABI,
  ZEROLANCE_REPUTATION_NFT_ABI,
  ZEROLANCE_ESCROW_VAULT_ABI,
  ZEROLANCE_TASK_REGISTRY_ABI,
  ZEROLANCE_ARBITRATION_ABI,
  MOCK_USDC_ABI,
  ZEROLANCE_TOKEN_ABI,
  ZEROLANCE_TEE_VERIFIER_ABI,
  ZEROLANCE_POINTS_LEDGER_ABI,
  ERC20_ABI,
} from "@zerolance/config/abis";
